Reference dataset catalogue page update
uktrade/data-workspace pull request #1605
Opened 2021-09-02 21:02 UTC by sekharpanja

### Description of change
This PR:
    Updates reference dataset catalogue page to new design
    Adds columns and code snippets
    adds new overflow columns page
    adds new enhanced preview page
    allows data download as both csv and json

### Checklist

* [ ] Have tests been added to cover any changes?

2021-09-03 05:29 UTC, markhigham commented on dataworkspace/dataworkspace/apps/datasets/views.py
> +    get_code_snippets_for_refereance_table,
`refereance`

2021-09-03 05:33 UTC, markhigham commented on dataworkspace/dataworkspace/static/data-grid.js
> +    let rowData = [];
`let` is only partially supported in IE11. This is probably OK but it may be worth testing

2021-09-03 05:52 UTC, markhigham requested changes
A couple of comments inline

2021-09-03 08:39 UTC, niross commented on dataworkspace/dataworkspace/apps/datasets/views.py
> +        except (DataSet.DoesNotExist, SourceTable.DoesNotExist):
Should this be `ReferenceDataset.DoesNotExist`?

2021-09-03 08:42 UTC, niross commented on dataworkspace/dataworkspace/apps/datasets/views.py
> +        except (DataSet.DoesNotExist, SourceTable.DoesNotExist):
Actually saying that could we just use `get_object_or_404`?

2021-09-06 15:35 UTC, niross approved these changes

2021-09-06 16:19 UTC, michalc approved these changes

2021-09-08 11:44 UTC, merged